spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
#    active: prod

jwt:
  issuer: subinuer
  secret: U//kDSMz7KbODt3QFAJbzxu0CDlqcOUAZmELz2ArZnLBq0QeHFRuzrxbDU+gr+Nb8L0mYnyAV03Vp4a9aXDHEA==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer
